logger:
  mode: development
crawlers:
  - type: file
    path: \data
    site: jira
  - type: file
    path: \data2
    site: confluence
kafka:
  brokers:
    - 192.168.80.132:9092
  topic: train-data