logger:
  mode: development
crawlers:
  - type: jira
    domain: jira.example.com
    api_token: your-jira-api-token
    interval: 10m
  - type: confluence
    domain: confluence.example.com
    api_token: your-confluence-api-token
    interval: 15m
kafka:
  brokers:
    - kafka-server:9092
  topic: train-data